services:
  - type: web
    name: courier-system
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: "Courier Management"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:mU5s5Ab4E3PKL2LNtVOjr/pmzAEXPZJNNh/vnMPdy0M=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://courier-system-5e0l.onrender.com"
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: elyseenshombo5@gmail.com
      - key: MAIL_PASSWORD
        value: pswh_bnok_rpgt_palo
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: elyseenshombo5@gmail.com
      - key: MAIL_FROM_NAME
        value: "Courier Management"
      - key: BROADCAST_DRIVER
        value: pusher
      - key: PUSHER_APP_ID
        value: "2067321"
      - key: PUSHER_APP_KEY
        value: c7322f8171253fb89f9a
      - key: PUSHER_APP_SECRET
        value: d0dd1c88f91935146934
      - key: PUSHER_APP_CLUSTER
        value: mt1
      - key: VITE_PUSHER_APP_KEY
        value: c7322f8171253fb89f9a
      - key: VITE_PUSHER_APP_CLUSTER
        value: mt1
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: "6379"
